// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "mall-api/internal/logic/address"
	_ "mall-api/internal/logic/cart"
	_ "mall-api/internal/logic/category"
	_ "mall-api/internal/logic/goods"
	_ "mall-api/internal/logic/index"
	_ "mall-api/internal/logic/order"
	_ "mall-api/internal/logic/search"
	_ "mall-api/internal/logic/user"
)
