// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// AdminUser is the golang structure of table tb_newbee_mall_admin_user for DAO operations like Where/Data.
type AdminUser struct {
	g.Meta        `orm:"table:tb_newbee_mall_admin_user, do:true"`
	AdminUserId   interface{} // 管理员id
	LoginUserName interface{} // 管理员登陆名称
	LoginPassword interface{} // 管理员登陆密码
	NickName      interface{} // 管理员显示昵称
	Locked        interface{} // 是否锁定 0未锁定 1已锁定无法登陆
}
