// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Carousel is the golang structure of table tb_newbee_mall_carousel for DAO operations like Where/Data.
type Carousel struct {
	g.Meta       `orm:"table:tb_newbee_mall_carousel, do:true"`
	CarouselId   interface{} // 首页轮播图主键id
	CarouselUrl  interface{} // 轮播图
	RedirectUrl  interface{} // 点击后的跳转地址(默认不跳转)
	CarouselRank interface{} // 排序值(字段越大越靠前)
	IsDeleted    interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime   *gtime.Time // 创建时间
	CreateUser   interface{} // 创建者id
	UpdateTime   *gtime.Time // 修改时间
	UpdateUser   interface{} // 修改者id
}
