// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoodsCategory is the golang structure of table tb_newbee_mall_goods_category for DAO operations like Where/Data.
type GoodsCategory struct {
	g.Meta        `orm:"table:tb_newbee_mall_goods_category, do:true"`
	CategoryId    interface{} // 分类id
	CategoryLevel interface{} // 分类级别(1-一级分类 2-二级分类 3-三级分类)
	ParentId      interface{} // 父分类id
	CategoryName  interface{} // 分类名称
	CategoryRank  interface{} // 排序值(字段越大越靠前)
	IsDeleted     interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime    *gtime.Time // 创建时间
	CreateUser    interface{} // 创建者id
	UpdateTime    *gtime.Time // 修改时间
	UpdateUser    interface{} // 修改者id
}
