// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoodsInfo is the golang structure of table tb_newbee_mall_goods_info for DAO operations like Where/Data.
type GoodsInfo struct {
	g.Meta             `orm:"table:tb_newbee_mall_goods_info, do:true"`
	GoodsId            interface{} // 商品表主键id
	GoodsName          interface{} // 商品名
	GoodsIntro         interface{} // 商品简介
	GoodsCategoryId    interface{} // 关联分类id
	GoodsCoverImg      interface{} // 商品主图
	GoodsCarousel      interface{} // 商品轮播图
	GoodsDetailContent interface{} // 商品详情
	OriginalPrice      interface{} // 商品价格
	SellingPrice       interface{} // 商品实际售价
	StockNum           interface{} // 商品库存数量
	Tag                interface{} // 商品标签
	GoodsSellStatus    interface{} // 商品上架状态 1-下架 0-上架
	CreateUser         interface{} // 添加者主键id
	CreateTime         *gtime.Time // 商品添加时间
	UpdateUser         interface{} // 修改者主键id
	UpdateTime         *gtime.Time // 商品修改时间
}
