// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// IndexConfig is the golang structure of table tb_newbee_mall_index_config for DAO operations like Where/Data.
type IndexConfig struct {
	g.Meta      `orm:"table:tb_newbee_mall_index_config, do:true"`
	ConfigId    interface{} // 首页配置项主键id
	ConfigName  interface{} // 显示字符(配置搜索时不可为空，其他可为空)
	ConfigType  interface{} // 1-搜索框热搜 2-搜索下拉框热搜 3-(首页)热销商品 4-(首页)新品上线 5-(首页)为你推荐
	GoodsId     interface{} // 商品id 默认为0
	RedirectUrl interface{} // 点击后的跳转地址(默认不跳转)
	ConfigRank  interface{} // 排序值(字段越大越靠前)
	IsDeleted   interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime  *gtime.Time // 创建时间
	CreateUser  interface{} // 创建者id
	UpdateTime  *gtime.Time // 最新修改时间
	UpdateUser  interface{} // 修改者id
}
