// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OrderItem is the golang structure of table tb_newbee_mall_order_item for DAO operations like Where/Data.
type OrderItem struct {
	g.Meta        `orm:"table:tb_newbee_mall_order_item, do:true"`
	OrderItemId   interface{} // 订单关联购物项主键id
	OrderId       interface{} // 订单主键id
	GoodsId       interface{} // 关联商品id
	GoodsName     interface{} // 下单时商品的名称(订单快照)
	GoodsCoverImg interface{} // 下单时商品的主图(订单快照)
	SellingPrice  interface{} // 下单时商品的价格(订单快照)
	GoodsCount    interface{} // 数量(订单快照)
	CreateTime    *gtime.Time // 创建时间
}
