// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// OrderAddress is the golang structure of table tb_newbee_mall_order_address for DAO operations like Where/Data.
type OrderAddress struct {
	g.Meta        `orm:"table:tb_newbee_mall_order_address, do:true"`
	OrderId       interface{} //
	UserName      interface{} // 收货人姓名
	UserPhone     interface{} // 收货人手机号
	ProvinceName  interface{} // 省
	CityName      interface{} // 城
	RegionName    interface{} // 区
	DetailAddress interface{} // 收件详细地址(街道/楼宇/单元)
}
