// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table tb_newbee_mall_order for DAO operations like Where/Data.
type Order struct {
	g.Meta      `orm:"table:tb_newbee_mall_order, do:true"`
	OrderId     interface{} // 订单表主键id
	OrderNo     interface{} // 订单号
	UserId      interface{} // 用户主键id
	TotalPrice  interface{} // 订单总价
	PayStatus   interface{} // 支付状态:0.未支付,1.支付成功,-1:支付失败
	PayType     interface{} // 0.无 1.支付宝支付 2.微信支付
	PayTime     *gtime.Time // 支付时间
	OrderStatus interface{} // 订单状态:0.待支付 1.已支付 2.配货完成 3:出库成功 4.交易成功 -1.手动关闭 -2.超时关闭 -3.商家关闭
	ExtraInfo   interface{} // 订单body
	IsDeleted   interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime  *gtime.Time // 创建时间
	UpdateTime  *gtime.Time // 最新修改时间
}
