// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ShoppingCartItem is the golang structure of table tb_newbee_mall_shopping_cart_item for DAO operations like Where/Data.
type ShoppingCartItem struct {
	g.Meta     `orm:"table:tb_newbee_mall_shopping_cart_item, do:true"`
	CartItemId interface{} // 购物项主键id
	UserId     interface{} // 用户主键id
	GoodsId    interface{} // 关联商品id
	GoodsCount interface{} // 数量(最大为5)
	IsDeleted  interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 最新修改时间
}
