// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserToken is the golang structure of table tb_newbee_mall_user_token for DAO operations like Where/Data.
type UserToken struct {
	g.Meta     `orm:"table:tb_newbee_mall_user_token, do:true"`
	UserId     interface{} // 用户主键id
	Token      interface{} // token值(32位字符串)
	UpdateTime *gtime.Time // 修改时间
	ExpireTime *gtime.Time // token过期时间
}
