// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table tb_newbee_mall_user for DAO operations like Where/Data.
type User struct {
	g.Meta        `orm:"table:tb_newbee_mall_user, do:true"`
	UserId        interface{} // 用户主键id
	NickName      interface{} // 用户昵称
	LoginName     interface{} // 登陆名称(默认为手机号)
	PasswordMd5   interface{} // MD5加密后的密码
	IntroduceSign interface{} // 个性签名
	IsDeleted     interface{} // 注销标识字段(0-正常 1-已注销)
	LockedFlag    interface{} // 锁定标识字段(0-未锁定 1-已锁定)
	CreateTime    *gtime.Time // 注册时间
}
