// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserAddress is the golang structure of table tb_newbee_mall_user_address for DAO operations like Where/Data.
type UserAddress struct {
	g.Meta        `orm:"table:tb_newbee_mall_user_address, do:true"`
	AddressId     interface{} //
	UserId        interface{} // 用户主键id
	UserName      interface{} // 收货人姓名
	UserPhone     interface{} // 收货人手机号
	DefaultFlag   interface{} // 是否为默认 0-非默认 1-是默认
	ProvinceName  interface{} // 省
	CityName      interface{} // 城
	RegionName    interface{} // 区
	DetailAddress interface{} // 收件详细地址(街道/楼宇/单元)
	IsDeleted     interface{} // 删除标识字段(0-未删除 1-已删除)
	CreateTime    *gtime.Time // 添加时间
	UpdateTime    *gtime.Time // 修改时间
}
