// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminUserDao is the data access object for table tb_newbee_mall_admin_user.
type AdminUserDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns AdminUserColumns // columns contains all the column names of Table for convenient usage.
}

// AdminUserColumns defines and stores column names for table tb_newbee_mall_admin_user.
type AdminUserColumns struct {
	AdminUserId   string // 管理员id
	LoginUserName string // 管理员登陆名称
	LoginPassword string // 管理员登陆密码
	NickName      string // 管理员显示昵称
	Locked        string // 是否锁定 0未锁定 1已锁定无法登陆
}

//  adminUserColumns holds the columns for table tb_newbee_mall_admin_user.
var adminUserColumns = AdminUserColumns{
	AdminUserId:   "admin_user_id",
	LoginUserName: "login_user_name",
	LoginPassword: "login_password",
	NickName:      "nick_name",
	Locked:        "locked",
}

// NewAdminUserDao creates and returns a new DAO object for table data access.
func NewAdminUserDao() *AdminUserDao {
	return &AdminUserDao{
		group:   "default",
		table:   "tb_newbee_mall_admin_user",
		columns: adminUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AdminUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AdminUserDao) Columns() AdminUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AdminUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
