// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminUserTokenDao is the data access object for table tb_newbee_mall_admin_user_token.
type AdminUserTokenDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns AdminUserTokenColumns // columns contains all the column names of Table for convenient usage.
}

// AdminUserTokenColumns defines and stores column names for table tb_newbee_mall_admin_user_token.
type AdminUserTokenColumns struct {
	AdminUserId string // 用户主键id
	Token       string // token值(32位字符串)
	UpdateTime  string // 修改时间
	ExpireTime  string // token过期时间
}

//  adminUserTokenColumns holds the columns for table tb_newbee_mall_admin_user_token.
var adminUserTokenColumns = AdminUserTokenColumns{
	AdminUserId: "admin_user_id",
	Token:       "token",
	UpdateTime:  "update_time",
	ExpireTime:  "expire_time",
}

// NewAdminUserTokenDao creates and returns a new DAO object for table data access.
func NewAdminUserTokenDao() *AdminUserTokenDao {
	return &AdminUserTokenDao{
		group:   "default",
		table:   "tb_newbee_mall_admin_user_token",
		columns: adminUserTokenColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminUserTokenDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AdminUserTokenDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AdminUserTokenDao) Columns() AdminUserTokenColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AdminUserTokenDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminUserTokenDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminUserTokenDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
