// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CarouselDao is the data access object for table tb_newbee_mall_carousel.
type CarouselDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns CarouselColumns // columns contains all the column names of Table for convenient usage.
}

// CarouselColumns defines and stores column names for table tb_newbee_mall_carousel.
type CarouselColumns struct {
	CarouselId   string // 首页轮播图主键id
	CarouselUrl  string // 轮播图
	RedirectUrl  string // 点击后的跳转地址(默认不跳转)
	CarouselRank string // 排序值(字段越大越靠前)
	IsDeleted    string // 删除标识字段(0-未删除 1-已删除)
	CreateTime   string // 创建时间
	CreateUser   string // 创建者id
	UpdateTime   string // 修改时间
	UpdateUser   string // 修改者id
}

//  carouselColumns holds the columns for table tb_newbee_mall_carousel.
var carouselColumns = CarouselColumns{
	CarouselId:   "carousel_id",
	CarouselUrl:  "carousel_url",
	RedirectUrl:  "redirect_url",
	CarouselRank: "carousel_rank",
	IsDeleted:    "is_deleted",
	CreateTime:   "create_time",
	CreateUser:   "create_user",
	UpdateTime:   "update_time",
	UpdateUser:   "update_user",
}

// NewCarouselDao creates and returns a new DAO object for table data access.
func NewCarouselDao() *CarouselDao {
	return &CarouselDao{
		group:   "default",
		table:   "tb_newbee_mall_carousel",
		columns: carouselColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CarouselDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CarouselDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CarouselDao) Columns() CarouselColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CarouselDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CarouselDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CarouselDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
