// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ShoppingCartItemDao is the data access object for table tb_newbee_mall_shopping_cart_item.
type ShoppingCartItemDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns ShoppingCartItemColumns // columns contains all the column names of Table for convenient usage.
}

// ShoppingCartItemColumns defines and stores column names for table tb_newbee_mall_shopping_cart_item.
type ShoppingCartItemColumns struct {
	CartItemId string // 购物项主键id
	UserId     string // 用户主键id
	GoodsId    string // 关联商品id
	GoodsCount string // 数量(最大为5)
	IsDeleted  string // 删除标识字段(0-未删除 1-已删除)
	CreateTime string // 创建时间
	UpdateTime string // 最新修改时间
}

//  shoppingCartItemColumns holds the columns for table tb_newbee_mall_shopping_cart_item.
var shoppingCartItemColumns = ShoppingCartItemColumns{
	CartItemId: "cart_item_id",
	UserId:     "user_id",
	GoodsId:    "goods_id",
	GoodsCount: "goods_count",
	IsDeleted:  "is_deleted",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// NewShoppingCartItemDao creates and returns a new DAO object for table data access.
func NewShoppingCartItemDao() *ShoppingCartItemDao {
	return &ShoppingCartItemDao{
		group:   "default",
		table:   "tb_newbee_mall_shopping_cart_item",
		columns: shoppingCartItemColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ShoppingCartItemDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ShoppingCartItemDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ShoppingCartItemDao) Columns() ShoppingCartItemColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ShoppingCartItemDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ShoppingCartItemDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ShoppingCartItemDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
