// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model"
)

type IAddress interface {
	GetUserDefaultAddress(ctx context.Context, userId string) (*model.AddressOutputItem, error)
	GetUserAllAddress(ctx context.Context, userId string) (*[]model.AddressOutputItem, error)
	GetAddressById(ctx context.Context, addressId string) (*model.AddressOutputItem, error)
	AddAddress(ctx context.Context, userId string, req *model.AddAddressInput) (*model.AddressOutputItem, error)
}

var localAddress IAddress

func Address() IAddress {
	if localAddress == nil {
		panic("implement not found for interface IAddress, forgot register?")
	}
	return localAddress
}

func RegisterAddress(i IAddress) {
	localAddress = i
}
