// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model"
)

type ICart interface {
	GetUserCart(ctx context.Context, userId int) (*[]model.UserCartOutput, error)
	DelShopCart(ctx context.Context, userId int, cartId string) bool
	AddShopCart(ctx context.Context, userId int, goodsId int, goodsCount int) (*model.AddCartOutput, error)
	UpdateShopCart(ctx context.Context, userId int, cartItemId int, goodsCount int) (*model.UpdateCartOutput, error)
	GetCartGoodsById(ctx context.Context, cartItemId int) (*model.CartSettleOutput, error)
	CartSettle(ctx context.Context, cartItemIds []string) (res []model.CartSettleOutput, err error)
}

var localCart ICart

func Cart() ICart {
	if localCart == nil {
		panic("implement not found for interface ICart, forgot register?")
	}
	return localCart
}

func RegisterCart(i ICart) {
	localCart = i
}
