// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model/entity"
)

type ICategory interface {
	GetCategoryByParentId(ctx context.Context, parentId int) (*[]entity.GoodsCategory, error)
	GetCategoryById(ctx context.Context, categoryId int) (*entity.GoodsCategory, error)
	GetCategoryByLevel(ctx context.Context, categoryLevel int) (*[]entity.GoodsCategory, error)
	GetCategory(ctx context.Context) *[]interface{}
	GetCategoryTree(ctx context.Context, res *[]interface{}, parentId int)
}

var localCategory ICategory

func Category() ICategory {
	if localCategory == nil {
		panic("implement not found for interface ICategory, forgot register?")
	}
	return localCategory
}

func RegisterCategory(i ICategory) {
	localCategory = i
}
