// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model"
)

type IGoods interface {
	Detail(ctx context.Context, goodId string) (*model.GoodsDetailOutput, error)
}

var localGoods IGoods

func Goods() IGoods {
	if localGoods == nil {
		panic("implement not found for interface IGoods, forgot register?")
	}
	return localGoods
}

func RegisterGoods(i IGoods) {
	localGoods = i
}
