// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model"
)

type IIndex interface {
	GetCarousels(ctx context.Context) ([]model.IndexCarouselItemOutput, error)
	GetIndexGoods(ctx context.Context, indexGoodsType int) ([]model.GoodsItemOutput, error)
	GetHotGoods(ctx context.Context) ([]model.GoodsItemOutput, error)
	GetNewGoods(ctx context.Context) ([]model.GoodsItemOutput, error)
	GetRecommendGoods(ctx context.Context) ([]model.GoodsItemOutput, error)
}

var localIndex IIndex

func Index() IIndex {
	if localIndex == nil {
		panic("implement not found for interface IIndex, forgot register?")
	}
	return localIndex
}

func RegisterIndex(i IIndex) {
	localIndex = i
}
