// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"mall-api/internal/model"
)

type IOrder interface {
	GetOrderGoodsInfos(ctx context.Context, cartItemIds []int) (*[]model.CartSettleOutput, error)
	SaveOrder(ctx context.Context, userId string, addressId int, cartItemIds []int) (string, error)
	GetOrderGoodsSnapshotById(ctx context.Context, orderId int) ([]model.GetCartOutput, error)
	GetOrderIdByNo(ctx context.Context, orderNo string) (orderId int, err error)
	GetOrderByUser(ctx context.Context, userId string, orderStatus int, page model.PageReq) (*model.OrderListOutput, error)
	GetOrderDetail(ctx context.Context, orderNo string) (*model.OrderDetailOutput, error)
	PayOrder(ctx context.Context, orderNo string, payType string) (*model.PayOrderOutput, error)
}

var localOrder IOrder

func Order() IOrder {
	if localOrder == nil {
		panic("implement not found for interface IOrder, forgot register?")
	}
	return localOrder
}

func RegisterOrder(i IOrder) {
	localOrder = i
}
