// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalAdminUserTokenDao is internal type for wrapping internal DAO implements.
type internalAdminUserTokenDao = *internal.AdminUserTokenDao

// adminUserTokenDao is the data access object for table tb_newbee_mall_admin_user_token.
// You can define custom methods on it to extend its functionality as you wish.
type adminUserTokenDao struct {
	internalAdminUserTokenDao
}

var (
	// AdminUserToken is globally public accessible object for table tb_newbee_mall_admin_user_token operations.
	AdminUserToken = adminUserTokenDao{
		internal.NewAdminUserTokenDao(),
	}
)

// Fill with you ideas below.
