// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalGoodsCategoryDao is internal type for wrapping internal DAO implements.
type internalGoodsCategoryDao = *internal.GoodsCategoryDao

// goodsCategoryDao is the data access object for table tb_newbee_mall_goods_category.
// You can define custom methods on it to extend its functionality as you wish.
type goodsCategoryDao struct {
	internalGoodsCategoryDao
}

var (
	// GoodsCategory is globally public accessible object for table tb_newbee_mall_goods_category operations.
	GoodsCategory = goodsCategoryDao{
		internal.NewGoodsCategoryDao(),
	}
)

// Fill with you ideas below.
