// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalIndexConfigDao is internal type for wrapping internal DAO implements.
type internalIndexConfigDao = *internal.IndexConfigDao

// indexConfigDao is the data access object for table tb_newbee_mall_index_config.
// You can define custom methods on it to extend its functionality as you wish.
type indexConfigDao struct {
	internalIndexConfigDao
}

var (
	// IndexConfig is globally public accessible object for table tb_newbee_mall_index_config operations.
	IndexConfig = indexConfigDao{
		internal.NewIndexConfigDao(),
	}
)

// Fill with you ideas below.
