// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalOrderAddressDao is internal type for wrapping internal DAO implements.
type internalOrderAddressDao = *internal.OrderAddressDao

// orderAddressDao is the data access object for table tb_newbee_mall_order_address.
// You can define custom methods on it to extend its functionality as you wish.
type orderAddressDao struct {
	internalOrderAddressDao
}

var (
	// OrderAddress is globally public accessible object for table tb_newbee_mall_order_address operations.
	OrderAddress = orderAddressDao{
		internal.NewOrderAddressDao(),
	}
)

// Fill with you ideas below.
