// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalOrderItemDao is internal type for wrapping internal DAO implements.
type internalOrderItemDao = *internal.OrderItemDao

// orderItemDao is the data access object for table tb_newbee_mall_order_item.
// You can define custom methods on it to extend its functionality as you wish.
type orderItemDao struct {
	internalOrderItemDao
}

var (
	// OrderItem is globally public accessible object for table tb_newbee_mall_order_item operations.
	OrderItem = orderItemDao{
		internal.NewOrderItemDao(),
	}
)

// Fill with you ideas below.
