// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalOrderDao is internal type for wrapping internal DAO implements.
type internalOrderDao = *internal.OrderDao

// orderDao is the data access object for table tb_newbee_mall_order.
// You can define custom methods on it to extend its functionality as you wish.
type orderDao struct {
	internalOrderDao
}

var (
	// Order is globally public accessible object for table tb_newbee_mall_order operations.
	Order = orderDao{
		internal.NewOrderDao(),
	}
)

// Fill with you ideas below.
