// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalShoppingCartItemDao is internal type for wrapping internal DAO implements.
type internalShoppingCartItemDao = *internal.ShoppingCartItemDao

// shoppingCartItemDao is the data access object for table tb_newbee_mall_shopping_cart_item.
// You can define custom methods on it to extend its functionality as you wish.
type shoppingCartItemDao struct {
	internalShoppingCartItemDao
}

var (
	// ShoppingCartItem is globally public accessible object for table tb_newbee_mall_shopping_cart_item operations.
	ShoppingCartItem = shoppingCartItemDao{
		internal.NewShoppingCartItemDao(),
	}
)

// Fill with you ideas below.
