// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall-api/internal/dao/internal"
)

// internalUserTokenDao is internal type for wrapping internal DAO implements.
type internalUserTokenDao = *internal.UserTokenDao

// userTokenDao is the data access object for table tb_newbee_mall_user_token.
// You can define custom methods on it to extend its functionality as you wish.
type userTokenDao struct {
	internalUserTokenDao
}

var (
	// UserToken is globally public accessible object for table tb_newbee_mall_user_token operations.
	UserToken = userTokenDao{
		internal.NewUserTokenDao(),
	}
)

// Fill with you ideas below.
