// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminUserToken is the golang structure for table admin_user_token.
type AdminUserToken struct {
	AdminUserId int64       `json:"adminUserId" description:"用户主键id"`
	Token       string      `json:"token"       description:"token值(32位字符串)"`
	UpdateTime  *gtime.Time `json:"updateTime"  description:"修改时间"`
	ExpireTime  *gtime.Time `json:"expireTime"  description:"token过期时间"`
}
