// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AdminUser is the golang structure for table admin_user.
type AdminUser struct {
	AdminUserId   int64  `json:"adminUserId"   description:"管理员id"`
	LoginUserName string `json:"loginUserName" description:"管理员登陆名称"`
	LoginPassword string `json:"loginPassword" description:"管理员登陆密码"`
	NickName      string `json:"nickName"      description:"管理员显示昵称"`
	Locked        int    `json:"locked"        description:"是否锁定 0未锁定 1已锁定无法登陆"`
}
