// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Carousel is the golang structure for table carousel.
type Carousel struct {
	CarouselId   int         `json:"carouselId"   description:"首页轮播图主键id"`
	CarouselUrl  string      `json:"carouselUrl"  description:"轮播图"`
	RedirectUrl  string      `json:"redirectUrl"  description:"点击后的跳转地址(默认不跳转)"`
	CarouselRank int         `json:"carouselRank" description:"排序值(字段越大越靠前)"`
	IsDeleted    int         `json:"isDeleted"    description:"删除标识字段(0-未删除 1-已删除)"`
	CreateTime   *gtime.Time `json:"createTime"   description:"创建时间"`
	CreateUser   int         `json:"createUser"   description:"创建者id"`
	UpdateTime   *gtime.Time `json:"updateTime"   description:"修改时间"`
	UpdateUser   int         `json:"updateUser"   description:"修改者id"`
}
