// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoodsCategory is the golang structure for table goods_category.
type GoodsCategory struct {
	CategoryId    int64       `json:"categoryId"    description:"分类id"`
	CategoryLevel int         `json:"categoryLevel" description:"分类级别(1-一级分类 2-二级分类 3-三级分类)"`
	ParentId      int64       `json:"parentId"      description:"父分类id"`
	CategoryName  string      `json:"categoryName"  description:"分类名称"`
	CategoryRank  int         `json:"categoryRank"  description:"排序值(字段越大越靠前)"`
	IsDeleted     int         `json:"isDeleted"     description:"删除标识字段(0-未删除 1-已删除)"`
	CreateTime    *gtime.Time `json:"createTime"    description:"创建时间"`
	CreateUser    int         `json:"createUser"    description:"创建者id"`
	UpdateTime    *gtime.Time `json:"updateTime"    description:"修改时间"`
	UpdateUser    int         `json:"updateUser"    description:"修改者id"`
}
