// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoodsInfo is the golang structure for table goods_info.
type GoodsInfo struct {
	GoodsId            uint64      `json:"goodsId"            description:"商品表主键id"`
	GoodsName          string      `json:"goodsName"          description:"商品名"`
	GoodsIntro         string      `json:"goodsIntro"         description:"商品简介"`
	GoodsCategoryId    int64       `json:"goodsCategoryId"    description:"关联分类id"`
	GoodsCoverImg      string      `json:"goodsCoverImg"      description:"商品主图"`
	GoodsCarousel      string      `json:"goodsCarousel"      description:"商品轮播图"`
	GoodsDetailContent string      `json:"goodsDetailContent" description:"商品详情"`
	OriginalPrice      int         `json:"originalPrice"      description:"商品价格"`
	SellingPrice       int         `json:"sellingPrice"       description:"商品实际售价"`
	StockNum           uint        `json:"stockNum"           description:"商品库存数量"`
	Tag                string      `json:"tag"                description:"商品标签"`
	GoodsSellStatus    int         `json:"goodsSellStatus"    description:"商品上架状态 1-下架 0-上架"`
	CreateUser         int         `json:"createUser"         description:"添加者主键id"`
	CreateTime         *gtime.Time `json:"createTime"         description:"商品添加时间"`
	UpdateUser         int         `json:"updateUser"         description:"修改者主键id"`
	UpdateTime         *gtime.Time `json:"updateTime"         description:"商品修改时间"`
}
