// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// IndexConfig is the golang structure for table index_config.
type IndexConfig struct {
	ConfigId    int64       `json:"configId"    description:"首页配置项主键id"`
	ConfigName  string      `json:"configName"  description:"显示字符(配置搜索时不可为空，其他可为空)"`
	ConfigType  int         `json:"configType"  description:"1-搜索框热搜 2-搜索下拉框热搜 3-(首页)热销商品 4-(首页)新品上线 5-(首页)为你推荐"`
	GoodsId     int64       `json:"goodsId"     description:"商品id 默认为0"`
	RedirectUrl string      `json:"redirectUrl" description:"点击后的跳转地址(默认不跳转)"`
	ConfigRank  int         `json:"configRank"  description:"排序值(字段越大越靠前)"`
	IsDeleted   int         `json:"isDeleted"   description:"删除标识字段(0-未删除 1-已删除)"`
	CreateTime  *gtime.Time `json:"createTime"  description:"创建时间"`
	CreateUser  int         `json:"createUser"  description:"创建者id"`
	UpdateTime  *gtime.Time `json:"updateTime"  description:"最新修改时间"`
	UpdateUser  int         `json:"updateUser"  description:"修改者id"`
}
