// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// OrderItem is the golang structure for table order_item.
type OrderItem struct {
	OrderItemId   int64       `json:"orderItemId"   description:"订单关联购物项主键id"`
	OrderId       int64       `json:"orderId"       description:"订单主键id"`
	GoodsId       int64       `json:"goodsId"       description:"关联商品id"`
	GoodsName     string      `json:"goodsName"     description:"下单时商品的名称(订单快照)"`
	GoodsCoverImg string      `json:"goodsCoverImg" description:"下单时商品的主图(订单快照)"`
	SellingPrice  int         `json:"sellingPrice"  description:"下单时商品的价格(订单快照)"`
	GoodsCount    int         `json:"goodsCount"    description:"数量(订单快照)"`
	CreateTime    *gtime.Time `json:"createTime"    description:"创建时间"`
}
