// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ShoppingCartItem is the golang structure for table shopping_cart_item.
type ShoppingCartItem struct {
	CartItemId int64       `json:"cartItemId" description:"购物项主键id"`
	UserId     int64       `json:"userId"     description:"用户主键id"`
	GoodsId    int64       `json:"goodsId"    description:"关联商品id"`
	GoodsCount int         `json:"goodsCount" description:"数量(最大为5)"`
	IsDeleted  int         `json:"isDeleted"  description:"删除标识字段(0-未删除 1-已删除)"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"最新修改时间"`
}
