// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserToken is the golang structure for table user_token.
type UserToken struct {
	UserId     int64       `json:"userId"     description:"用户主键id"`
	Token      string      `json:"token"      description:"token值(32位字符串)"`
	UpdateTime *gtime.Time `json:"updateTime" description:"修改时间"`
	ExpireTime *gtime.Time `json:"expireTime" description:"token过期时间"`
}
