// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	UserId        int64       `json:"userId"        description:"用户主键id"`
	NickName      string      `json:"nickName"      description:"用户昵称"`
	LoginName     string      `json:"loginName"     description:"登陆名称(默认为手机号)"`
	PasswordMd5   string      `json:"passwordMd5"   description:"MD5加密后的密码"`
	IntroduceSign string      `json:"introduceSign" description:"个性签名"`
	IsDeleted     int         `json:"isDeleted"     description:"注销标识字段(0-正常 1-已注销)"`
	LockedFlag    int         `json:"lockedFlag"    description:"锁定标识字段(0-未锁定 1-已锁定)"`
	CreateTime    *gtime.Time `json:"createTime"    description:"注册时间"`
}
